import {
  FlaskConical,
  ScanLine,
  HeartPulse,
  BriefcaseMedical,
  BadgeCheck,
  Clock,
  HeartHandshake,
  MapPin,
  Phone,
  MessageCircle,
  ArrowRight,
  ArrowUpRight,
  Check,
  Plus,
  Search,
  ShoppingBag,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Menu,
  ShieldCheck,
  Timer,
  FileText,
  Contact,
  CreditCard,
  Stethoscope,
  Microscope,
  CalendarClock,
  Sparkles,
  Ear,
  Activity,
  Moon,
  Baby,
  Waves,
  Wind,
  Mic,
  Syringe,
  Volume2,
  ClipboardList,
  Trash2,
} from "lucide-react";

const MAP = {
  flask: FlaskConical,
  scan: ScanLine,
  "heart-pulse": HeartPulse,
  "briefcase-medical": BriefcaseMedical,
  "badge-check": BadgeCheck,
  clock: Clock,
  "heart-handshake": HeartHandshake,
  "map-pin": MapPin,
  phone: Phone,
  whatsapp: MessageCircle,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  check: Check,
  plus: Plus,
  search: Search,
  bag: ShoppingBag,
  x: X,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  menu: Menu,
  shield: ShieldCheck,
  timer: Timer,
  file: FileText,
  id: Contact,
  card: CreditCard,
  stethoscope: Stethoscope,
  microscope: Microscope,
  "calendar-clock": CalendarClock,
  sparkles: Sparkles,
  ear: Ear,
  activity: Activity,
  moon: Moon,
  baby: Baby,
  waves: Waves,
  wind: Wind,
  mic: Mic,
  syringe: Syringe,
  volume: Volume2,
  clipboard: ClipboardList,
  trash: Trash2,
};

export default function Icon({ name, className = "h-5 w-5", ...rest }) {
  const Cmp = MAP[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={1.7} aria-hidden="true" {...rest} />;
}
